apiVersion: v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: eforms-app
  name: eforms-app
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
  minReadySeconds: 30 
  selector:
    matchLabels:
      app.kubernetes.io/name: eforms-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: eforms-app
    spec:
      containers:
      - name: eforms
        image: eacloudacr.azurecr.io/eacloud/eforms:V1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m        
---
apiVersion: v1
kind: Service
metadata:
  name: eforms-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    matchLabels:
      app.kubernetes.io/name: eforms-app