apiVersion: apps/v1
kind: Deployment
metadata:
  name: eforms-deployment
  labels:
    app: eforms
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eforms
  template:
    metadata:
      labels:
        app: eforms
    spec:
      containers:
      - name: eforms
        image: eacloudacr.azurecr.io/eacloud/eforms:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: eforms-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
   app: eforms
