apiVersion: apps/v1
kind: Deployment
metadata:
  name: eforms-deployment
  labels:
    app: eforms
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eforms
  minReadySeconds: 30
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: eforms
    spec:
      containers:
      - name: eforms
        image: eacloudacr.azurecr.io/eacloud/eforms:0.0.4
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: eforms-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
   app: eforms        
---        
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS, DELETE"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*.*"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"    
  name: eforms-ingress
spec:
  rules:
    - host: eforms.eastus2.cloudapp.azure.com
      http:
        paths:
          - backend:
              serviceName: eforms-service
              servicePort: 80
            path: /
  tls:
      - hosts:
          - eforms.eastus2.cloudapp.azure.com
        secretName: aks-ingress-tls